services:
  - docker

script:
  - docker build -t local_mysql -f local_mysql.Dockerfile .
  - docker run -p 3306:3306 local_mysql &
  - docker build -t ramp_db -f travis.Dockerfile .
  - docker run --network=host --privileged=true ramp_db